### ISSUE TITLE
What would one need to do to get this running on BlackIce II board?

### ISSUE THREAD

**Issue by philtomson** [grahamedgecombe/icicle#2]
What would one need to do to get this running on BlackIce II board?

**Comment by grahamedgecombe** [comment]
Hi,

You'll need to create a new `.mk` and `.pcf` file in the `boards` directory - it's probably easiest to base these on the existing files.

Based on the information available at https://www.tindie.com/products/Folknology/blackice-ii/, the variables in the `.mk` file should be set to:

* `SPEED` should be set to `hx`.
* `DEVICE` should be set to `8k`. (Although the BlackIce II has a 4k part, the 4k and 8k parts are the same internally.)
* `PACKAGE` should be set to `tq144:4k`.
* `FREQ_OSC` should be set to `100`.

Based on the schematics and https://github.com/mystorm-org/BlackIce-II/blob/master/examples/common/blackice-ii.pcf, the pin mappings in the `.pcf` file should be set as follows:

* `clk` should be set to 129.
* `leds[0]`, `leds[1]`, `leds[2]` and `leds[3]` should be set to 71, 67, 68 and 70. The remaining four led outputs can be set to any unused pin (selecting the pins connected to an unused PMOD connector is probably a good choice).
* `flash_*` are currently unused and can be set to any unused pin. I'm not sure if the BlackIce II has an SPI flash chip connected directly to the FPGA, so this might need thinking about when SPI flash support is added.
* `uart_rx` should be set to 88.
* `uart_tx` should be set to 85.

Then follow the instructions in the README, setting `BOARD` to the name you chose (e.g. `BOARD=xyz` will use `boards/xyz.mk` and `boards/xyz.pcf`).

I don't have a BlackIce II board, so all of the above is completely untested - so please check carefully before trying it in case I've made a mistake that will damage your board!

If you get it working I'd be happy to accept a PR :)

**Comment by grahamedgecombe** [comment]
Closing as PR #3 has been merged, thanks :)
